TareasMVC/Controllers/UsuariosController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data;
using System.Security.Claims;
using TareasMVC.Migrations;
using TareasMVC.Models;
using TareasMVC.Servicios;

namespace TareasMVC.Controllers
{
    public class UsuariosController : Controller
    {
        private readonly UserManager<IdentityUser> userManager;
        private readonly SignInManager<IdentityUser> signInManager;
        private readonly ApplicationDbContext context;

        public UsuariosController(
            UserManager<IdentityUser> userManager,
            SignInManager<IdentityUser> signInManager,
            ApplicationDbContext context


            ) { // userManager utilziamos para trabajar con nuestros usuarios 
            //aplicationdbcontext es la pirza central de entityframeworkcore y que para hacer queries a las tablas tenemos que usar una instancia de esta
            //recordar que el aplicationdbcontext lo configuramos comos ervicio e la clase program
            this.userManager = userManager;
            this.signInManager = signInManager;
            this.context = context;
            //identityuser es la entidad configurada en al clase program que representa a un usuario
        }
        [AllowAnonymous] // nos permite indicar que cualquier usuario este identificado o no puede invocar esta accion 
        public IActionResult Registro()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Registro(RegistroViewModel modelo)
        {
            if (!ModelState.IsValid)
            {
                return View(modelo);    
            }

            var usuario = new IdentityUser()
            {
                Email = modelo.Email,
                UserName = modelo.Email
            };

            var resultado = await userManager.CreateAsync(usuario , password : modelo.Password);
            if (resultado.Succeeded)
            {
                await signInManager.SignInAsync(usuario, isPersistent: true);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                foreach(var error in resultado.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description); // porque es un error que no se relacione con un campo especifico sino que es a nivel de modelo
                }
                return View(modelo);
            }
        }

        [AllowAnonymous]
        public IActionResult Login(string mensaje = null)
        {
            if(mensaje is not null)
            {
                ViewData["mensaje"] = mensaje;  //pasando el viewdata hacia la vistra
            }
            return View();  
        }


        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Login(LoginViewModel modelo)
        {
            if(!ModelState.IsValid)
            {
                return View(modelo);
            }

            var resultado
                = await signInManager.PasswordSignInAsync(modelo.Email, modelo.Password, modelo.Recuerdame, lockoutOnFailure: false);
            //lockoutOnFailure : si el usuario se equivoca mcuhas veces en iniciar sesion en esa cuenta la cerraremos, ponemosen false

            if(resultado.Succeeded)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Nombre del usuario o password incorrectos");
                return View(modelo);
            }

        }

        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(IdentityConstants.ApplicationScheme);
            return RedirectToAction("Index", "Home"); 
        }

        [AllowAnonymous]
        [HttpGet]
        public ChallengeResult LoginExterno(string proveedor, string urlRetorno = null)//challengeresult significa que vamos aredirigir al usuario donde va a poder logerase , el retorno opcional
        {
            var urlRedireccion = Url.Action("RegistrarUsuarioExterno", values: new { urlRetorno }); //nombre de la accion que va a recibir la data del usuario
            var propiedades = signInManager.ConfigureExternalAuthenticationProperties(proveedor, urlRedireccion); //configura las propiedades de autenticacion externa 
            return new ChallengeResult(proveedor, propiedades); 
        }

        [AllowAnonymous]
        public async Task<IActionResult> RegistrarUsuario(string urlRetorno = null, string remoteError = null) //EL REM,OTE ERROR HARA REFERENCIA AL URL QE NOS PUIEDE DEVOLVER EL PROVEEDOR EN CASOD E CUALQUIER ERROR
        {
            urlRetorno = urlRetorno ?? Url.Content("~/"); //SI ES NULO SE LE ENVIARA AL ROOT
            var mensaje = "";
            if (remoteError is not null) {
                mensaje = $"Error del proveedor externo : { remoteError}";
                return RedirectToAction("login", routeValues: new { mensaje }); //si hay algun error redireciono al llogin con ese mensaje
            }

            var info = await signInManager.GetExternalLoginInfoAsync();
            if(info is null)
            {
                mensaje = "Error, cargando la data de login externo";
                return RedirectToAction("login", routeValues: new { mensaje });
            }

            var resultadoLoginExterno
                = await signInManager.ExternalLoginSignInAsync(info.LoginProvider,info.ProviderKey, isPersistent : true, bypassTwoFactor : true);//usamos un login pero suando la informacion del login externo

            //YA LA CUENTA EXISTE DEL PROVEEDOR INTERNO Y NNOI TENEMSI QUE HACER NADA
            //HEMOS LOGEADO CON LOS DATOS PROVENIENTES Y FUE TODO OK, EL SUUARIO TIENE CUENA
            if(resultadoLoginExterno.Succeeded)
            {
                return LocalRedirect(urlRetorno);
            }
            string email = "";

            //usuaio no tiene una cuenta co nosotros y teen,so que crearlla                     
            if(info.Principal.HasClaim(c => c.Type == ClaimTypes.Email))
            {
                email = info.Principal.FindFirstValue(ClaimTypes.Email);
            }
            else
            {
                mensaje = "Error leyendo el email del usuario proveedor";
                return RedirectToAction("login", routeValues: new { mensaje });
            }

            var usuario = new IdentityUser { Email = email, UserName = email };
            var resultadoCrearUsuario = await userManager.CreateAsync(usuario); 

            if(!resultadoCrearUsuario.Succeeded)
            {
                mensaje = resultadoCrearUsuario.Errors.First().Description;
                return RedirectToAction("login", routeValues: new { mensaje });
            }

            //si fue exitoso vamos a agregar ese login externo a la tabla de logins
            var resultadoAgregarLogin = await userManager.AddLoginAsync(usuario, info);
            if (resultadoAgregarLogin.Succeeded)
            {
                await signInManager.SignInAsync(usuario, isPersistent: true, info.LoginProvider);//ahora si todo esta OK logearemos al usuario
                return LocalRedirect(urlRetorno);
            }

            mensaje = "Ha ocurrido un error al agreegar el login";
            return RedirectToAction("login", routeValues: new { mensaje });


        }

        [HttpGet]
        [Authorize(Roles = Constantes.RolAdmin)] //para evitar el ingreso mediante el link a un recurso no autorizado
        public async Task<IActionResult> Listado(string mensaje = null)
        {
            var usuarios = await context.Users.Select(u => new UsuarioViewModel
            {
                Email = u.Email,
            }).ToListAsync();
            //EN ESTE CASO QUEREMOS TRAER SOLO LA CO,UMNA DEL EMAIL POR ESO MEDIANTE EL SELECT SELECIONAMOS CUAL Y NO TRA
            //EMOS TODAS LA COLUMNAS POR DEFECTO
            var modelo = new UsuariosListadoViewModel();
            modelo.Usuarios = usuarios;
            modelo.Mensaje = mensaje;
            return View(modelo);    
        }

        [HttpPost]
        [Authorize(Roles = Constantes.RolAdmin)]
        public async Task<IActionResult> HacerAdmin(string email)
        {
            var usuario = await context.Users.Where( u => u.Email == email).FirstOrDefaultAsync();
            //firstordefault significa el primer valor ol el valor por defecto de usuario que es null
            if(usuario is null)
            {
                return NotFound();
            }
            await userManager.AddToRoleAsync(usuario, Constantes.RolAdmin);
            return RedirectToAction("Listado",routeValues:new {mensaje = "Rol asignado correctamente a" + email});

        }

        [HttpPost]
        [Authorize(Roles = Constantes.RolAdmin)]
        public async Task<IActionResult> RemoverAdmin(string email)
        {
            var usuario = await context.Users.Where(u => u.Email == email).FirstOrDefaultAsync();
            //firstordefault significa el primer valor ol el valor por defecto de usuario que es null
            if (usuario is null)
            {
                return NotFound();
            }
            await userManager.RemoveFromRoleAsync(usuario, Constantes.RolAdmin);
            return RedirectToAction("Listado", routeValues: new { mensaje = "Rol removido correctamente a" + email });

        }
    }
 }

TareasMVC/Views/Shared/_Layout.cshtml
@using TareasMVC.Servicios;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TareasMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TareasMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TareasMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        @if (User.IsInRole(Constantes.RolAdmin))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Listado">Listado de Usuarios</a>
                            </li>
                        }
                       
                    </ul>
                    <partial name="_LinksLogin" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TareasMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <partial name="_TraduccionesJS" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery-ui/jquery-ui.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/knockout/3.5.0/knockout-min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TareasMVC/Views/Shared/_LinksLogin.cshtml
 @using Microsoft.AspNetCore.Identity
 @inject SignInManager<IdentityUser> SignInManager

<ul class="navbar-nav">
    @if (SignInManager.IsSignedIn(User)) //SI EL USUARIO ESTA LOGEADO LE PASAMOS EL USUARIO
    {
        <li class="nav-item">
            <span class="nav-link text-dark">Hola, @User.Identity.Name</span>
        </li>
        <li class="nav-item">
              <form class="form-inline" asp-action="logout" asp-controller="usuarios">
                  <button type="submit" class="nav-link btn btn-link text-dark">
                      Logout
                  </button>
              </form>
        </li>
    }else{
        <li class="nav-item">
            <a class="nav-link dark-text" asp-controller="usuarios" asp-action="Registro">Registro</a>
        </li>
        <li class="nav-item">
            <a class="nav-link dark-text" asp-controller="usuarios" asp-action="Login">Login</a>
        </li>
    }
</ul>

TareasMVC/Views/Shared/_TraduccionesJS.cshtml
@using Microsoft.AspNetCore.Mvc.Localization;
@inject IViewLocalizer localizer;

<script>
    const mensajeDeError = "@localizer["mensajeDeError"]";
</script>